In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("Student_performance.csv")

In [ ]:
df

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,student_performance
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.300,Excellent
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.700,Poor
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.000,Excellent
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.900,Good
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.000,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,18,female,b.tech,4.86,70.7,yes,4.1,good,mixed,high,moderate,69.500,Good
629996,629996,21,female,ba,7.08,54.4,yes,4.5,average,mixed,low,moderate,78.900,Excellent
629997,629997,24,male,bca,0.64,44.2,yes,4.3,poor,online videos,low,moderate,19.599,Poor
629998,629998,20,male,b.com,1.54,75.1,yes,8.2,average,group study,high,moderate,59.100,Average
629999,629999,18,other,b.tech,3.94,75.3,yes,5.8,poor,online videos,low,easy,37.200,Poor

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
df_model = df.copy()

In [ ]:
# df_model.columns = df_model.columns.str.strip()
# for col in df_model.select_dtypes(include='object').columns:
#     df_model[col] = df_model[col].str.strip()

# Drop ID & Leakage
if 'id' in df_model.columns: df_model.drop(columns=['id'], inplace=True)
if 'exam_score' in df_model.columns: df_model.drop(columns=['exam_score'], inplace=True)

In [ ]:
df_model

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,student_performance
0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,Excellent
1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,Poor
2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,Excellent
3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,Good
4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,female,b.tech,4.86,70.7,yes,4.1,good,mixed,high,moderate,Good
629996,21,female,ba,7.08,54.4,yes,4.5,average,mixed,low,moderate,Excellent
629997,24,male,bca,0.64,44.2,yes,4.3,poor,online videos,low,moderate,Poor
629998,20,male,b.com,1.54,75.1,yes,8.2,average,group study,high,moderate,Average
629999,18,other,b.tech,3.94,75.3,yes,5.8,poor,online videos,low,easy,Poor

In [ ]:
df['gender'].value_counts()

gender
other     211097
male      210593
female    208310
Name: count, dtype: int64

In [ ]:
#  Ordinal Encoding
ordinal_maps = {
    'sleep_quality': {'poor': 0, 'average': 1, 'good': 2},
    'facility_rating': {'low': 0, 'medium': 1, 'high': 2},
    'exam_difficulty': {'easy': 0, 'moderate': 1, 'hard': 2}
}
for col, mapping in ordinal_maps.items():
    df_model[col] = df_model[col].map(mapping)

# Binary Encoding
df_model['internet_access'] = df_model['internet_access'].map({'yes': 1, 'no': 0})
le = LabelEncoder()
cols_to_encode = ['gender', 'course', 'study_method','student_performance']

for col in cols_to_encode:
    df_model[col] = le.fit_transform(df_model[col])

In [ ]:
df_model.head()

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,student_performance
0,21,0,1,7.91,98.8,0,4.9,1,3,0,0,1
1,18,2,6,4.95,94.8,1,4.7,0,4,1,1,3
2,20,0,1,4.68,92.6,1,5.8,0,0,2,1,1
3,19,1,1,2.00,49.5,1,8.3,1,1,2,1,2
4,23,1,5,7.65,86.9,1,9.6,2,4,2,0,1

In [ ]:
df_model['student_performance'].value_counts(normalize=True)

student_performance
0    0.251286
3    0.250538
2    0.250076
1    0.248100
Name: proportion, dtype: float64

In [ ]:
# # Creating  Features
# df_model['study_efficiency'] = df_model['study_hours'] * (df_model['class_attendance'] / 100)
# df_model['consistency'] = df_model['study_hours'] * df_model['sleep_hours']
# df_model['wellness_index'] = df_model['sleep_quality'] * df_model['sleep_hours']
# df_model['risk_factor'] = df_model['exam_difficulty'] / (df_model['study_hours'] + 0.1)

# Removing Dependency
# cols_to_remove = ['study_hours', 'class_attendance', 'sleep_hours']
# df_model.drop(columns=cols_to_remove, inplace=True)

In [ ]:
# Target ko alag kiya (Text format mein hi hai)
y = df_model['student_performance']
X = df_model.drop(columns=['student_performance'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# print(f"Mean of Scaled Data (Approx 0): {np.mean(X_train_scaled):.4f}")
# print(f"Std Dev of Scaled Data (Approx 1): {np.std(X_train_scaled):.4f}")

Mean of Scaled Data (Approx 0): 0.0000
Std Dev of Scaled Data (Approx 1): 1.0000

In [ ]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

model = HistGradientBoostingClassifier(max_iter=100, learning_rate=0.1, random_state=42)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)

# 4. Accuracy Check
acc = accuracy_score(y_test, y_pred)

print("\n" + "="*50)
print(f"FINAL MODEL ACCURACY: {acc*100:.2f}%")
print("="*50)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

==================================================
FINAL MODEL ACCURACY: 64.85%
==================================================

Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.52      0.53     31662
           1       0.75      0.76      0.76     31261
           2       0.53      0.55      0.54     31509
           3       0.76      0.77      0.77     31568

    accuracy                           0.65    126000
   macro avg       0.65      0.65      0.65    126000
weighted avg       0.65      0.65      0.65    126000

In [ ]:
from lightgbm import LGBMClassifier

models = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42
)

models.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.080842 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 595
[LightGBM] [Info] Number of data points in the train set: 504000, number of used features: 11
[LightGBM] [Info] Start training from score -1.381165
[LightGBM] [Info] Start training from score -1.393927
[LightGBM] [Info] Start training from score -1.385985
[LightGBM] [Info] Start training from score -1.384146

LGBMClassifier(learning_rate=0.05, n_estimators=300, random_state=42)

In [ ]:
y_preds = models.predict(X_test)

# 4. Accuracy Check
accs = accuracy_score(y_test, y_preds)

print("\n" + "="*50)
print(f"FINAL MODEL ACCURACY: {accs*100:.2f}%")
print("="*50)

print("\nClassification Report:")
print(classification_report(y_test, y_preds))

==================================================
FINAL MODEL ACCURACY: 64.97%
==================================================

Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.52      0.53     31662
           1       0.76      0.76      0.76     31261
           2       0.54      0.55      0.54     31509
           3       0.76      0.77      0.77     31568

    accuracy                           0.65    126000
   macro avg       0.65      0.65      0.65    126000
weighted avg       0.65      0.65      0.65    126000

In [ ]:
import pandas as pd

importance = models.feature_importances_

feat_imp = pd.DataFrame({
    'feature': X_train.columns,
    'importance': importance
}).sort_values(by='importance', ascending=False)

print(feat_imp)

             feature  importance
3        study_hours       10277
4   class_attendance        9194
6        sleep_hours        4272
8       study_method        3714
7      sleep_quality        2940
9    facility_rating        2400
0                age        1050
2             course         993
10   exam_difficulty         487
1             gender         486
5    internet_access         187

In [ ]:
import joblib

joblib.dump(models, "student_performance_model.pkl")

['student_performance_model.pkl']